### ISSUE TITLE
API Key Missing Error

### ISSUE THREAD

**Issue by SethNJohnson** [kevindb/cf-mailchimp#2]
Every time I try to call a method I get "API Key Missing" even though it is set and entered into the "password" field.  Was the API updated?  

I am using Lucee 4.5 on Ubuntu 12.04.

**Comment by SethNJohnson** [comment]
Fixed this issue by putting the API KEY in the Authorization header.  Please see:

https://stackoverflow.com/questions/35293829/401-unauthorized-error-when-sending-put-request-to-mailchimp-api-v3-0-using-cold

**Comment by kevindb** [comment]
I can't find anything in MailChimp's documentation that instructs to use the Authorization header. Would you please provide a link?

This is what I found, which is why cf-mailchimp is using HTTP Basic Authentication:
http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/#authentication

**Comment by kevindb** [comment]
Closing until more documentation can be found.
